/**
 * Created by guguyanhua on 16/1/23.
 */
var Holder = {
  a1: require('./a1.jpg'),

  a2: require('./a2.jpg'),
  a3: require('./a3.jpg'),

  a4: require('./a4.jpg'),
  a5: require('./a5.jpg'),
  a6: require('./a6.jpg'),
  a7: require('./a7.jpg'),
  a8: require('./a8.jpg'),
  a9: require('./a9.jpg'),
  a10: require('./a10.jpg'),
  b1: require('./b1.jpg'),
  b2: require('./b2.jpg'),
  b3: require('./b3.jpg'),
  b4: require('./b4.jpg'),
  b5: require('./b5.jpg'),
  b6: require('./b6.jpg'),
  b7: require('./b7.jpg'),
  b8: require('./b8.jpg'),
  b9: require('./b9.jpg'),
  b10: require('./b10.jpg'),
  c1: require('./c1.jpg'),
  c2: require('./c2.jpg'),
  c3: require('./c3.jpg'),
  c4: require('./c4.jpg'),
  c5: require('./c5.jpg'),
  c6: require('./c6.jpg'),
  c7: require('./c7.jpg'),
  c8: require('./c8.jpg'),
  c9: require('./c9.jpg'),
  c10: require('./c10.jpg'),
  d1: require('./d1.jpg'),
  d2: require('./d2.jpg'),
  d3: require('./d3.jpg'),
  d4: require('./d4.jpg'),
  d5: require('./d5.jpg'),
  d6: require('./d6.jpg'),
  d7: require('./d7.jpg'),
  d8: require('./d8.jpg'),
  d9: require('./d9.jpg'),
  d10: require('./d10.jpg'),
  e1: require('./e1.jpg'),
  e2: require('./e2.jpg'),
  e3: require('./e3.jpg'),
  e4: require('./e4.jpg'),
  e5: require('./e5.jpg'),
  e6: require('./e6.jpg'),
  e7: require('./e7.jpg'),
  e8: require('./e8.jpg'),
  e9: require('./e9.jpg'),
  e10: require('./e10.jpg'),
  f1: require('./f1.jpg'),
  f2: require('./f2.jpg'),
  f3: require('./f3.jpg'),
  f4: require('./f4.jpg'),
  f5: require('./f5.jpg'),
  f6: require('./f6.jpg'),
  f7: require('./f7.jpg'),
  f8: require('./f8.jpg'),
  f9: require('./f9.jpg'),
  f10: require('./f10.jpg'),
  me_logo:require('./me_logo.png'),
  result_logo:require('./result_logo.png'),
  signin_logo:require('./signin_logo.png'),
  start_02:require('./start_02.png'),
  video_loading:require('./video_loading.png')
}

module.exports = Holder;